# BC 카드 소비 데이터 분석 (2)

* 2020년 3월 카드 소비 데이터 : bc_card_out2020_03.txt
  - 레코드 수가 100만개 이상
  - \t으로 분리된 csv 파일
  - 전처리된 데이터가 저장되어 있음

## 1. 데이터 로딩 to DataFrame
- 전처리하여 csv로 저장한 파일 '201906.csv'을 판다스 dataframe으로 로딩 (encoding='utf-8', index_col=0)
- 앞부분 데이터 확인
- 전체 데이터 수 확인

In [5]:
import pandas as pd
bc_card = pd.read_csv('bc_card_out2020_03.txt', sep='\t', encoding='utf-8')
bc_card

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,202003,11,서울특별시,1168,강남구,11680750,수서동,30,생활,40,...,내국인,11,서울특별시,1168,강남구,2,20대,1,7927440,1089
1,202003,11,서울특별시,1129,성북구,11290660,길음1동,30,생활,70,...,내국인,11,서울특별시,1129,성북구,1,40대,4,274100,25
2,202003,11,서울특별시,1144,마포구,11440555,아현동,30,생활,40,...,내국인,11,서울특별시,1114,중구,1,60대 이상,5,34395725,808
3,202003,11,서울특별시,1126,중랑구,11260590,상봉2동,30,생활,40,...,내국인,11,서울특별시,1126,중랑구,2,20대,1,31860800,3699
4,202003,11,서울특별시,1168,강남구,11680630,대치4동,30,생활,62,...,내국인,41,경기도,4146,용인시,2,50대,4,2546487,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589489,202003,11,서울특별시,1126,중랑구,11260575,면목3.8동,80,음식,80,...,내국인,11,서울특별시,1144,마포구,2,50대,4,115000,4
1589490,202003,11,서울특별시,1162,관악구,11620695,신림동,80,음식,80,...,내국인,11,서울특별시,1174,강동구,2,40대,3,40000,3
1589491,202003,11,서울특별시,1168,강남구,11680640,역삼1동,40,쇼핑,42,...,내국인,11,서울특별시,1141,서대문구,2,30대,1,89230,3
1589492,202003,11,서울특별시,1156,영등포구,11560700,대림1동,80,음식,80,...,내국인,11,서울특별시,1121,광진구,2,50대,4,84500,3
1589493,202003,11,서울특별시,1126,중랑구,11260680,신내1동,80,음식,80,...,내국인,41,경기도,4115,의정부시,2,20대,1,47800,15

In [6]:
# 서울에 거주 중인 고객데이터 추출
index1 = bc_card[bc_card['CSTMR_MEGA_CTY_NM'] != '서울특별시'].index
seoul_card_df = bc_card.drop(index1)
seoul_card_df.reset_index(drop=True, inplace=True)
seoul_card_df

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,202003,11,서울특별시,1168,강남구,11680750,수서동,30,생활,40,...,내국인,11,서울특별시,1168,강남구,2,20대,1,7927440,1089
1,202003,11,서울특별시,1129,성북구,11290660,길음1동,30,생활,70,...,내국인,11,서울특별시,1129,성북구,1,40대,4,274100,25
2,202003,11,서울특별시,1144,마포구,11440555,아현동,30,생활,40,...,내국인,11,서울특별시,1114,중구,1,60대 이상,5,34395725,808
3,202003,11,서울특별시,1126,중랑구,11260590,상봉2동,30,생활,40,...,내국인,11,서울특별시,1126,중랑구,2,20대,1,31860800,3699
4,202003,11,서울특별시,1130,강북구,11305660,인수동,30,생활,92,...,내국인,11,서울특별시,1130,강북구,1,50대,4,508970,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901067,202003,11,서울특별시,1168,강남구,11680750,수서동,85,유흥,86,...,내국인,11,서울특별시,1156,영등포구,1,30대,1,17000,3
901068,202003,11,서울특별시,1126,중랑구,11260575,면목3.8동,80,음식,80,...,내국인,11,서울특별시,1144,마포구,2,50대,4,115000,4
901069,202003,11,서울특별시,1162,관악구,11620695,신림동,80,음식,80,...,내국인,11,서울특별시,1174,강동구,2,40대,3,40000,3
901070,202003,11,서울특별시,1168,강남구,11680640,역삼1동,40,쇼핑,42,...,내국인,11,서울특별시,1141,서대문구,2,30대,1,89230,3
901071,202003,11,서울특별시,1156,영등포구,11560700,대림1동,80,음식,80,...,내국인,11,서울특별시,1121,광진구,2,50대,4,84500,3

In [7]:
# 서울에 비거주 중인 고객데이터 추출
index2 = bc_card[bc_card['CSTMR_MEGA_CTY_NM'] == '서울특별시'].index
# 해당 index 데이터 삭제한 df 저장
not_seoul_card_df = bc_card.drop(index2)
# 새로 생성한 df의 index 재정렬
not_seoul_card_df.reset_index(drop=True, inplace=True)
not_seoul_card_df

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,202003,11,서울특별시,1168,강남구,11680630,대치4동,30,생활,62,...,내국인,41,경기도,4146,용인시,2,50대,4,2546487,45
1,202003,11,서울특별시,1117,용산구,11170625,한강로동,30,생활,40,...,내국인,41,경기도,4111,수원시,2,40대,3,490425014,11932
2,202003,11,서울특별시,1156,영등포구,11560540,여의동,50,내구재,31,...,내국인,41,경기도,4117,안양시,2,40대,3,11098894,387
3,202003,11,서울특별시,1114,중구,11140540,회현동,10,T&E,11,...,내국인,28,인천광역시,2826,서구,1,30대,2,56176470,5772
4,202003,11,서울특별시,1153,구로구,11530540,구로3동,30,생활,40,...,내국인,41,경기도,4157,김포시,1,40대,3,590035029,5924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688417,202003,11,서울특별시,1168,강남구,11680640,역삼1동,40,쇼핑,40,...,내국인,26,부산광역시,2653,사상구,1,50대,4,360860,9
688418,202003,11,서울특별시,1165,서초구,11650550,반포본동,30,생활,61,...,내국인,29,광주광역시,2911,동구,1,30대,2,4100,3
688419,202003,11,서울특별시,1171,송파구,11710642,문정2동,30,생활,91,...,내국인,27,대구광역시,2729,달서구,1,40대,4,152100,4
688420,202003,11,서울특별시,1111,종로구,11110615,종로1.2.3.4가동,80,음식,80,...,내국인,45,전라북도,4513,군산시,2,60대 이상,5,26000,3
688421,202003,11,서울특별시,1126,중랑구,11260680,신내1동,80,음식,80,...,내국인,41,경기도,4115,의정부시,2,20대,1,47800,15

## 2. 서울시 거주/비거주 고객의 소비액 구하기
* 서울시 거주 고객 수와 소비액
    - 남성 고객수, 소비액
    - 여성 고객수, 소비액
* 서울시 비거주 고개 수와 소비액
    - 남성 고객수, 소비액
    - 여성 고객수, 소비액

In [17]:
seoul= pd.pivot_table(seoul_card_df, values=['AMT'], aggfunc='sum', index=['SEX_CTGO_CD'])
print('서울시 거주 고객의 고객수와 소비액 현황')
print(f"남성 : {len(seoul_card_df[seoul_card_df['SEX_CTGO_CD'] == 1]):,}명, {seoul.loc[1, 'AMT']:,}원")
print(f"여성 : {len(seoul_card_df[seoul_card_df['SEX_CTGO_CD'] == 2]):,}명, {seoul.loc[2, 'AMT']:,}원")

서울시 거주 고객의 고객수와 소비액 현황
남성 : 480,069명, 682,678,945,342원
여성 : 421,003명, 703,235,624,289원

In [18]:
not_seoul = pd.pivot_table(not_seoul_card_df, values=['AMT'], aggfunc='sum', index=['SEX_CTGO_CD'])
print('비서울시 거주 고객의 고객수와 소비액 현황')
print(f"남성 : {len(not_seoul_card_df[not_seoul_card_df['SEX_CTGO_CD'] == 1]):,}명, {not_seoul.loc[1, 'AMT']:,}원")
print(f"여성 : {len(not_seoul_card_df[not_seoul_card_df['SEX_CTGO_CD'] == 2]):,}명, {not_seoul.loc[2, 'AMT']:,}원")

비서울시 거주 고객의 고객수와 소비액 현황
남성 : 385,870명, 1,015,425,463,575원
여성 : 302,552명, 925,473,886,325원

### 3. 서울시 거주자 편의점 소비 건수와 소비액 구하기

In [28]:
seoul_cov = seoul_card_df[seoul_card_df['TP_BUZ_NO'] == 4010]
print('서울시 거주자 편의점 소비 건수와 소비액 현황')
print(f"소비 건수 : {seoul_cov['CNT'].sum(axis=0):,} , 소비액 : {seoul_cov['AMT'].sum(axis=0):,}")

서울시 거주자 편의점 소비 건수와 소비액 현황
소비 건수 : 10,113,011 , 소비액 : 66,513,977,146

### 4. 강남구 거주자의 강남구 내 소비액과 강남구 외 소비액 구하기

In [37]:
gangnam_gangnam = seoul_card_df[(seoul_card_df['CSTMR_CTY_RGN_NM'] == '강남구') & (seoul_card_df['CTY_RGN_NM'] == '강남구')]
gangnam_non_gangnam = seoul_card_df[(seoul_card_df['CSTMR_CTY_RGN_NM'] == '강남구') & (seoul_card_df['CTY_RGN_NM'] != '강남구')]
print("강남구 거주자의 강남구 내 소비액과 강남구 외 소비액 현황")
print(f"강남구 거주자의 강남구 내 소비액 : {gangnam_gangnam['AMT'].sum(axis=0):,}")
print(f"강남구 거주자의 강남구 외 소비액 : {gangnam_non_gangnam['AMT'].sum(axis=0):,}")

강남구 거주자의 강남구 내 소비액과 강남구 외 소비액 현황
강남구 거주자의 강남구 내 소비액 : 46,387,952,763
강남구 거주자의 강남구 외 소비액 : 62,203,324,642